// File generated by FlutterFire CLI.
// Replace the placeholder values below with the actual values from your
// Firebase project: https://console.firebase.google.com/
//
// How to get these values:
// 1. Go to https://console.firebase.google.com/
// 2. Select your project → Project Settings → General → Your apps
// 3. Click the web app (</>), copy the firebaseConfig values here.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS. '
          'Add your GoogleService-Info.plist and re-run FlutterFire CLI.',
        );
      default:
        return web; // fallback for desktop/other
    }
  }

  // ── WEB ────────────────────────────────────────────────────────────────────
  // TODO: Replace ALL values below with your real Firebase web app config.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBtPhAmjOiAEJ5pCqIQblL1e5x9bRP0blU",
  authDomain: "mobila-app-fd10e.firebaseapp.com",
  projectId: "mobila-app-fd10e",
  storageBucket: "mobila-app-fd10e.firebasestorage.app",
  messagingSenderId: "38104863071",
  appId: "1:38104863071:web:e16ad604d5c8a7bd3c26ea",
  measurementId: "G-KP8QEV0W81"
  );

  // ── ANDROID ────────────────────────────────────────────────────────────────
  // TODO: Replace ALL values below with your real google-services.json values.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'your-firebase-project-id',
    storageBucket: 'your-firebase-project-id.firebasestorage.app',
  );
}
