// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGmgKqOq2rgUbqVHHr_gtvy12Q-xQIuJE',
    appId: '1:327199587082:web:1f539900f76b46999ad8f3',
    messagingSenderId: '327199587082',
    projectId: 'again-43dc9',
    authDomain: 'again-43dc9.firebaseapp.com',
    databaseURL: 'https://again-43dc9-default-rtdb.firebaseio.com',
    storageBucket: 'again-43dc9.firebasestorage.app',
    measurementId: 'G-GB72RNRZXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYLmYWJRXcVzrfLGUw7wehIs5a6xMNt40',
    appId: '1:327199587082:android:22764975986e77039ad8f3',
    messagingSenderId: '327199587082',
    projectId: 'again-43dc9',
    databaseURL: 'https://again-43dc9-default-rtdb.firebaseio.com',
    storageBucket: 'again-43dc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeQ8nishWguFrm6BnnJdB1_fjpyS9LM2Y',
    appId: '1:327199587082:ios:98b4f8b8e40075989ad8f3',
    messagingSenderId: '327199587082',
    projectId: 'again-43dc9',
    databaseURL: 'https://again-43dc9-default-rtdb.firebaseio.com',
    storageBucket: 'again-43dc9.firebasestorage.app',
    iosBundleId: 'com.example.week5Authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeQ8nishWguFrm6BnnJdB1_fjpyS9LM2Y',
    appId: '1:327199587082:ios:98b4f8b8e40075989ad8f3',
    messagingSenderId: '327199587082',
    projectId: 'again-43dc9',
    databaseURL: 'https://again-43dc9-default-rtdb.firebaseio.com',
    storageBucket: 'again-43dc9.firebasestorage.app',
    iosBundleId: 'com.example.week5Authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGmgKqOq2rgUbqVHHr_gtvy12Q-xQIuJE',
    appId: '1:327199587082:web:0fa265918d1c71199ad8f3',
    messagingSenderId: '327199587082',
    projectId: 'again-43dc9',
    authDomain: 'again-43dc9.firebaseapp.com',
    databaseURL: 'https://again-43dc9-default-rtdb.firebaseio.com',
    storageBucket: 'again-43dc9.firebasestorage.app',
    measurementId: 'G-XP84DWN3RF',
  );
}
